package com.example.projetcv.model;

import com.example.projetcv.dao.ActivityRepository;
import com.example.projetcv.dao.CVRepository;
import com.example.projetcv.dao.PersonRepository;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.dao.DataIntegrityViolationException;

import java.time.LocalDate;
import java.util.Set;
import java.util.logging.Logger;

import static org.assertj.core.api.Assertions.assertThat;
import static org.junit.jupiter.api.Assertions.*;


@SpringBootTest
public class CVTest {

    @Autowired
    private PersonRepository personRepository;

    @Autowired
    private CVRepository cvRepository;

    @Autowired
    private ActivityRepository activityRepository;

    @BeforeEach
    public void cleanPersonTable(){
        personRepository.deleteAll();
        cvRepository.deleteAll();
        activityRepository.deleteAll();
    }

    Logger logger = Logger.getLogger(this.getClass().getName());

    //---------------------------------CONSTRAINTS TESTS---------------------------------

    @Test
    public void idAutoGeneratedTest(){
        Person person = Person.builder()
                .name("John")
                .firstName("Doe")
                .birthday(LocalDate.now())
                .email("john.doe@example.com")
                .passwordHash("lehash")
                .build();
        personRepository.save(person);
        CV cv = CV.builder()
                .person(person)
                .build();
        CV savedCV = cvRepository.save(cv);
        assertThat(savedCV.getId()).isNotNull();
    }


    @Test
    public void personNotNullableTest(){
        assertDoesNotThrow(()->{
            Person person = Person.builder()
                    .name("John")
                    .firstName("Doe")
                    .birthday(LocalDate.now())
                    .email("john.doe@example.com")
                    .passwordHash("lehash")
                    .build();
            personRepository.save(person);
            CV cv = CV.builder()
                    .person(person)
                    .build();
            cvRepository.save(cv);

        });
        Exception e = assertThrows(DataIntegrityViolationException.class, ()->{
            CV cv = CV.builder()
                    .build();
            cvRepository.save(cv);
        });
        //logger.info("e: " + e.getMessage());
        assertTrue(e.getMessage().contains("NOT NULL check constraint") && e.getMessage().contains("CV column: PERSON_ID"));
    }


    @Test
    public void activitiesCanBeEmptyTest() {
        assertDoesNotThrow(()->{
            Person person = Person.builder()
                    .name("John")
                    .firstName("Doe")
                    .birthday(LocalDate.now())
                    .email("john.doe@example.com")
                    .passwordHash("lehash")
                    .build();
            personRepository.save(person);
            CV cv = CV.builder()
                    .person(person)
                    .build();
            cvRepository.save(cv);
        });
        assertDoesNotThrow( ()->{
            Person person = Person.builder()
                    .name("Another-John")
                    .firstName("Doe")
                    .birthday(LocalDate.now())
                    .email("anotherjohn.doe@example.com")
                    .passwordHash("lehash")
                    .build();
            personRepository.save(person);
            CV cv = CV.builder()
                    .person(person)
                    .build();
            CV savedCV = cvRepository.save(cv); //save
            Activity activity = Activity.builder()
                    .cv(cv)
                    .year(2022)
                    .nature(Nature.PROJECT)
                    .title("Project Title")
                    .build();
            Activity savedActivity = activityRepository.save(activity);

            assertThat(personRepository.findById(person.getId()).get().getCv().getActivities().size()).isEqualTo(1);

        });
    }




}
