package com.example.projetcv.model;

import com.example.projetcv.dao.ActivityRepository;
import com.example.projetcv.dao.CVRepository;
import com.example.projetcv.dao.UserRepository;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.dao.DataIntegrityViolationException;

import java.time.LocalDate;
import java.util.List;
import java.util.Optional;
import java.util.logging.Logger;

import static org.assertj.core.api.Assertions.assertThat;
import static org.junit.jupiter.api.Assertions.*;


@SpringBootTest
public class CVTest {

    @Autowired
    private UserRepository userRepository;

    @Autowired
    private CVRepository cvRepository;

    @Autowired
    private ActivityRepository activityRepository;

    @BeforeEach
    public void cleanuserTable(){
        userRepository.deleteAll();
        cvRepository.deleteAll();
        activityRepository.deleteAll();
    }

    Logger logger = Logger.getLogger(this.getClass().getName());

    //---------------------------------CONSTRAINTS TESTS---------------------------------

    @Test
    public void idAutoGeneratedTest(){
        User user = User.builder()
                .name("John")
                .firstName("Doe")
                .birthday(LocalDate.now())
                .email("john.doe@example.com")
                .passwordHash("lehash")
                .build();
        userRepository.save(user);
        CV cv = CV.builder()
                .user(user)
                .build();
        CV savedCV = cvRepository.save(cv);
        assertThat(savedCV.getId()).isNotNull();
    }


    @Test
    public void userNotNullableTest(){
        assertDoesNotThrow(()->{
            User user = User.builder()
                    .name("John")
                    .firstName("Doe")
                    .birthday(LocalDate.now())
                    .email("john.doe@example.com")
                    .passwordHash("lehash")
                    .build();
            userRepository.save(user);
            CV cv = CV.builder()
                    .user(user)
                    .build();
            cvRepository.save(cv);

        });
        Exception e = assertThrows(DataIntegrityViolationException.class, ()->{
            CV cv = CV.builder()
                    .build();
            cvRepository.save(cv);
        });
        //logger.info("e: " + e.getMessage());
        assertTrue(e.getMessage().contains("NOT NULL check constraint") && e.getMessage().contains("CV column: user_ID"));
    }


    @Test
    public void activitiesCanBeEmptyTest() {
        assertDoesNotThrow(()->{
            User user = User.builder()
                    .name("John")
                    .firstName("Doe")
                    .birthday(LocalDate.now())
                    .email("john.doe@example.com")
                    .passwordHash("lehash")
                    .build();
            userRepository.save(user);
            CV cv = CV.builder()
                    .user(user)
                    .build();
            cvRepository.save(cv);
        });
        assertDoesNotThrow( ()->{
            User user = User.builder()
                    .name("Another-John")
                    .firstName("Doe")
                    .birthday(LocalDate.now())
                    .email("anotherjohn.doe@example.com")
                    .passwordHash("lehash")
                    .build();
            userRepository.save(user);
            CV cv = CV.builder()
                    .user(user)
                    .build();
            CV savedCV = cvRepository.save(cv); //save
            Activity activity = Activity.builder()
                    .cv(cv)
                    .year(2022)
                    .nature(Nature.PROJECT)
                    .title("Project Title")
                    .build();
            Activity savedActivity = activityRepository.save(activity);

            assertThat(userRepository.findById(user.getId()).get().getCv().getActivities().size()).isEqualTo(1);

        });
    }



    //---------------------------------CASCADE TESTS---------------------------------

    @Test
    public void deleteCascadeCVTest() {
        User user = User.builder()
                .name("John")
                .firstName("Doe")
                .birthday(LocalDate.now())
                .email("john.doe@example.com")
                .passwordHash("lehash")
                .build();
        User saveduser = userRepository.save(user);
        CV cv = CV.builder()
                .user(user)
                .build();
        CV savedCv = cvRepository.save(cv);
        Activity activity = Activity.builder()
                .cv(cv)
                .year(2022)
                .nature(Nature.PROJECT)
                .title("Project Title")
                .build();
        Activity savedActivity = activityRepository.save(activity);

        saveduser.setCv(null);             // Delete CV
        userRepository.save(saveduser);  //

        List<CV> retrievedCVs = cvRepository.findAll();
        assertThat(retrievedCVs.size()).isEqualTo(0);

        List<Activity> retrievedActivities = activityRepository.findAll();
        assertThat(retrievedActivities.size()).isEqualTo(0);
    }

    @Test
    public void deleteCascadeCVOppositeTest() {
        User user = User.builder()
                .name("John")
                .firstName("Doe")
                .birthday(LocalDate.now())
                .email("john.doe@example.com")
                .passwordHash("lehash")
                .build();
        User saveduser = userRepository.save(user);
        CV cv = CV.builder()
                .user(user)
                .build();
        CV savedCV = cvRepository.save(cv);
        Activity activity = Activity.builder()
                .cv(cv)
                .year(2022)
                .nature(Nature.PROJECT)
                .title("Project Title")
                .build();
        Activity savedActivity = activityRepository.save(activity);

        Optional<CV> retrievedCV = cvRepository.findById(savedCV.getId());
        retrievedCV.get().getActivities().removeIf(a -> a.getId().equals(savedActivity.getId()));  // Delete
        cvRepository.save(retrievedCV.get());                                                      //


        List<CV> retrievedCVs = cvRepository.findAll();
        assertThat(retrievedCVs.size()).isEqualTo(1);
        List<Activity> retrievedActivities = activityRepository.findAll();
        assertThat(retrievedActivities.size()).isEqualTo(0);

    }







}
