package com.example.projetcv.model;

import com.example.projetcv.dao.ActivityRepository;
import com.example.projetcv.dao.CVRepository;
import com.example.projetcv.dao.UserRepository;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.dao.DataIntegrityViolationException;
import org.springframework.dao.InvalidDataAccessApiUsageException;
import org.springframework.transaction.PlatformTransactionManager;
import org.springframework.transaction.TransactionDefinition;
import org.springframework.transaction.TransactionStatus;
import org.springframework.transaction.TransactionSystemException;
import org.springframework.transaction.support.DefaultTransactionDefinition;

import java.time.LocalDate;
import java.util.List;
import java.util.Optional;
import java.util.Set;
import java.util.logging.Logger;

import static org.assertj.core.api.Assertions.assertThat;
import static org.junit.jupiter.api.Assertions.*;


@SpringBootTest
public class UserTest {

    Logger logger = Logger.getLogger(this.getClass().getName());

    @Autowired
    private ActivityRepository activityRepository;

    @Autowired
    private CVRepository cvRepository;

    @Autowired
    private UserRepository userRepository;

    @BeforeEach
    public void cleanUserTable(){
        userRepository.deleteAll();
        cvRepository.deleteAll();
        activityRepository.deleteAll();
    }


    //---------------------------------CONSTRAINTS TESTS---------------------------------

    @Test
    public void idAutoGeneratedTest(){
            User user = User.builder()
                    .name("John")
                    .firstName("Doe")
                    .email("john.doe@example.com")
                    .birthday(LocalDate.now())
                    .passwordHash("lehash")
                    .build();
            User saveduser = userRepository.save(user);
            assertThat(saveduser.getId()).isNotNull();
    }

    @Test
    public void emailUniqueTest(){
        assertDoesNotThrow(()->{
            User user = User.builder()
                    .name("John")
                    .firstName("Doe")
                    .email("john.doe@example.com")
                    .birthday(LocalDate.now())
                    .passwordHash("lehash")
                    .build();
            userRepository.save(user);
        });
        Exception e = assertThrows(DataIntegrityViolationException.class, ()->{
            User user = User.builder()
                    .name("Max")
                    .firstName("Gui")
                    .email("john.doe@example.com")
                    .birthday(LocalDate.now())
                    .passwordHash("passhash")
                    .build();
            userRepository.save(user);
        });
        logger.info("e: " + e.getMessage());
        assertTrue(e.getMessage().contains("unique constraint") && e.getMessage().contains("user"));
    }

    @Test
    public void nameNotNullableTest(){
        assertDoesNotThrow(()->{
            User user = User.builder()
                    .name("John")
                    .firstName("Doe")
                    .email("john.doe@example.com")
                    .birthday(LocalDate.now())
                    .passwordHash("lehash")
                    .build();
            userRepository.save(user);
        });
        Exception e = assertThrows(DataIntegrityViolationException.class, ()->{
            User user = User.builder()
                    .firstName("Doe")
                    .email("anotherjohn.doe@example.com")
                    .birthday(LocalDate.now())
                    .passwordHash("lehash")
                    .build();
            userRepository.save(user);
        });
        logger.info("e: " + e.getMessage());
        assertTrue(e.getMessage().contains("NOT NULL check constraint") && e.getMessage().contains("USER column: NAME"));
    }

    @Test
    public void firstNameNotNullableTest(){
        assertDoesNotThrow(()->{
            User user = User.builder()
                    .name("John")
                    .firstName("Doe")
                    .email("john.doe@example.com")
                    .birthday(LocalDate.now())
                    .passwordHash("lehash")
                    .build();
            userRepository.save(user);
        });
        Exception e = assertThrows(DataIntegrityViolationException.class, ()->{
            User user = User.builder()
                    .name("John")
                    .email("anotherjohn.doe@example.com")
                    .birthday(LocalDate.now())
                    .passwordHash("lehash")
                    .build();
            userRepository.save(user);
        });
        logger.info("eeeeee: " + e.getMessage());
        assertTrue(e.getMessage().contains("NOT NULL check constraint") && e.getMessage().contains("USER column: FIRST_NAME"));
    }

    @Test
    public void emailNotNullableTest(){
        assertDoesNotThrow(()->{
            User user = User.builder()
                    .name("John")
                    .firstName("Doe")
                    .email("john.doe@example.com")
                    .birthday(LocalDate.now())
                    .passwordHash("lehash")
                    .build();
            userRepository.save(user);
        });
        Exception e = assertThrows(TransactionSystemException.class, ()->{
            User user = User.builder()
                    .name("JohnDeux")
                    .firstName("DoeDeux")
                    .birthday(LocalDate.now())
                    .passwordHash("lehash")
                    .build();
            userRepository.save(user);
        });
    }


    @Test
    public void websiteNullableTest(){
        assertDoesNotThrow(()->{
            User user = User.builder()
                    .name("John")
                    .firstName("Doe")
                    .email("john.doe@example.com")
                    .birthday(LocalDate.now())
                    .passwordHash("lehash")
                    .website("https://www.example.com")
                    .build();
            userRepository.save(user);
        });
        assertDoesNotThrow( ()->{
            User user = User.builder()
                    .name("AnotherJohn")
                    .firstName("Doe")
                    .email("anotherjohn.doe@example.com")
                    .birthday(LocalDate.now())
                    .passwordHash("lehash")
                    .build();
            userRepository.save(user);
        });
    }


    @Test
    public void birthdayNotNullableTest(){
        assertDoesNotThrow(()->{
            User user = User.builder()
                    .name("John")
                    .firstName("Doe")
                    .email("john.doe@example.com")
                    .birthday(LocalDate.now())
                    .passwordHash("lehash")
                    .build();
            userRepository.save(user);
        });
        Exception e = assertThrows(DataIntegrityViolationException.class, ()->{
            User user = User.builder()
                    .name("John")
                    .firstName("Doe")
                    .email("anotherjohn.doe@example.com")
                    .passwordHash("lehash")
                    .build();
            userRepository.save(user);
        });
        assertTrue(e.getMessage().contains("NOT NULL check constraint") && e.getMessage().contains("USER column: BIRTHDAY"));
    }

    @Test
    public void passwordHashNotNullableTest(){
        assertDoesNotThrow(()->{
            User user = User.builder()
                    .name("John")
                    .firstName("Doe")
                    .email("john.doe@example.com")
                    .birthday(LocalDate.now())
                    .passwordHash("lehash")
                    .build();
            userRepository.save(user);
        });
        Exception e = assertThrows(DataIntegrityViolationException.class, ()->{
            User user = User.builder()
                    .name("John")
                    .firstName("Doe")
                    .email("john.doe@example.com")
                    .birthday(LocalDate.now())
                    .build();
            userRepository.save(user);
        });
        assertTrue(e.getMessage().contains("NOT NULL check constraint") && e.getMessage().contains("USER column: PASSWORD_HASH"));
    }


    @Test
    public void cvNullableTest() {
        assertDoesNotThrow(()->{
            User user = User.builder()
                    .name("John")
                    .firstName("Doe")
                    .email("john.doe@example.com")
                    .birthday(LocalDate.now())
                    .passwordHash("lehash")
                    .build();
            userRepository.save(user);
        });
        assertDoesNotThrow( ()->{
            User user = User.builder()
                    .name("AnotherJohn")
                    .firstName("Doe")
                    .email("anotherjohn.doe@example.com")
                    .birthday(LocalDate.now())
                    .passwordHash("lehash")
                    .build();
            User saveduser = userRepository.save(user);
            CV cv = CV.builder()
                    .user(user) // Ajoute un CV à la userne
                    .build();
            cvRepository.save(cv);
        });
    }

    @Test
    public void rolesCanBeEmptyTest() {
        assertDoesNotThrow(()->{
            User user = User.builder()
                    .name("John")
                    .firstName("Doe")
                    .email("john.doe@example.com")
                    .birthday(LocalDate.now())
                    .passwordHash("lehash")
                    .build();
            userRepository.save(user);
        });
        assertDoesNotThrow( ()->{
            User user = User.builder()
                    .name("AnotherJohn")
                    .firstName("Doe")
                    .email("anotherjohn.doe@example.com")
                    .birthday(LocalDate.now())
                    .passwordHash("lehash")
                    .roles(Set.of("USER"))
                    .build();
            User saveduser = userRepository.save(user);
        });
    }


    //---------------------------------FETCH-TYPE TESTS---------------------------------


    /*
    @Autowired
    private PlatformTransactionManager transactionManager;

    @Test
    @Disabled // one-to-one NE PEUX PAS ETRE LAZY
    public void cvEagerFetchTest(){
        User saveduser;

        // Définition de la transaction 1
        TransactionDefinition transactionDefinition1 = new DefaultTransactionDefinition();
        TransactionStatus transactionStatus1 = transactionManager.getTransaction(transactionDefinition1);

        try {
            // Effectuer les opérations de la première transaction
            User user = User.builder()
                    .name("John")
                    .firstName("Doe")
                    .birthday(LocalDate.now())
                    .email("john.doe@example.com")
                    .passwordHash("lehash")
                    .build();
            saveduser = userRepository.save(user);
            CV cv = CV.builder()
                    .user(user)
                    .build();
            cvRepository.save(cv); //save
            Activity activity = Activity.builder()
                    .cv(cv)
                    .year(2022)
                    .nature(Nature.PROJECT)
                    .title("Project Title")
                    .build();
            activityRepository.save(activity);
            // Commit de la transaction 1
            transactionManager.commit(transactionStatus1);
        } catch (Exception e) {
            // Rollback de la transaction 1 en cas de l'échec
            transactionManager.rollback(transactionStatus1);
            throw e;
        }

        // Définition de la transaction 2
        TransactionDefinition transactionDefinition2 = new DefaultTransactionDefinition();
        TransactionStatus transactionStatus2 = transactionManager.getTransaction(transactionDefinition2);

        try {
            // Effectuer les opérations de la deuxième transaction
            Optional<User> retrieveduser = userRepository.findById(saveduser.getId());
            logger.info("retrieveduser::: " + retrieveduser);

            assertThat(retrieveduser).isPresent();
            assertThat(retrieveduser.get().getCv().getActivities().get(0).getTitle()).isEqualTo("Project Title");
            // Commit de la transaction 2
            transactionManager.commit(transactionStatus2);
        } catch (Exception e) {
            // Rollback de la transaction 2 en cas d'échec
            transactionManager.rollback(transactionStatus2);
            throw e;
        }

    }
*/

    //---------------------------------CASCADE TESTS---------------------------------


    @Test
    public void deleteCascadeCVTest() {
        User user = User.builder()
                .name("John")
                .firstName("Doe")
                .birthday(LocalDate.now())
                .email("john.doe@example.com")
                .passwordHash("lehash")
                .build();
        User saveduser = userRepository.save(user);
        CV cv = CV.builder()
                .user(user)
                .build();
        CV savedCV = cvRepository.save(cv);

        userRepository.deleteById(saveduser.getId());

        Optional<User> retrieveduser = userRepository.findById(user.getId());
        assertThat(retrieveduser).isNotPresent();
        Optional<CV> retrievedCV = cvRepository.findById(savedCV.getId());
        assertThat(retrievedCV).isNotPresent();
    }


    @Test
    public void deleteCascadeCVOppositeTest() {
        User user = User.builder()
                .name("John")
                .firstName("Doe")
                .birthday(LocalDate.now())
                .email("john.doe@example.com")
                .passwordHash("lehash")
                .build();
        User saveduser = userRepository.save(user);
        CV cv = CV.builder()
                .user(user)
                .build();
        CV savedCV = cvRepository.save(cv);

        user.setCv(null);             // Delete
        userRepository.save(user);  //


        Optional<User> retrievedUser = userRepository.findById(user.getId());
        assertThat(retrievedUser).isPresent();
        Optional<CV> retrievedCV = cvRepository.findById(savedCV.getId());
        assertThat(retrievedCV).isNotPresent();
    }


    @Test
    public void updateCascadeCVTest() {
        //create
        User user = User.builder()
                .name("John")
                .firstName("Doe")
                .birthday(LocalDate.now())
                .email("john.doe@example.com")
                .passwordHash("lehash")
                .build();
        User saveduser = userRepository.save(user);
        CV cv = CV.builder()
                .user(user)
                .build();
        CV savedCV = cvRepository.save(cv);
        Activity activity = Activity.builder()
                .cv(savedCV)
                .year(2022)
                .nature(Nature.PROJECT)
                .title("Project Title")
                .build();
        Activity savedActivity = activityRepository.save(activity);


        // Update user and cv
        User userFull = userRepository.findById(saveduser.getId()).get();
        userFull.setName("New-Name");
        CV cvFull = cvRepository.findById(savedCV.getId()).get();
        cvFull.getActivities().clear();
        userFull.setCv(cvFull);

        // Save ONLY user (cascade save cv)
        userRepository.save(userFull);

        // Check if user and cv are updated
        Optional<User> retrieveduser = userRepository.findById(user.getId());
        assertThat(retrieveduser).isPresent();
        assertThat(retrieveduser.get().getName()).isEqualTo("New-Name");
        Optional<CV> retrievedCV = cvRepository.findById(savedCV.getId());
        assertThat(retrievedCV).isPresent();
        assertThat(retrievedCV.get().getActivities().size()).isEqualTo(0);
    }

    @Test
    public void updateCascadeCVOppositeTest() {
        //create
        User user = User.builder()
                .name("John")
                .firstName("Doe")
                .birthday(LocalDate.now())
                .email("john.doe@example.com")
                .passwordHash("lehash")
                .build();
        User saveduser = userRepository.save(user);
        CV cv = CV.builder()
                .user(user)
                .build();
        CV savedCV = cvRepository.save(cv);
        Activity activity = Activity.builder()
                .cv(savedCV)
                .year(2022)
                .nature(Nature.PROJECT)
                .title("Project Title")
                .build();
        Activity savedActivity = activityRepository.save(activity);


        // Update user and cv
        User userFull = userRepository.findById(saveduser.getId()).get();
        userFull.setName("New-Name");
        CV cvFull = cvRepository.findById(savedCV.getId()).get();
        cvFull.getActivities().clear();
        //userFull.setCv(cvFull);
        cvFull.setUser(userFull);

        // Save ONLY user (cascade update cv)
        cvRepository.save(cvFull);

        // Check if user and cv are updated
        Optional<User> retrievedUser = userRepository.findById(user.getId());
        assertThat(retrievedUser).isPresent();
        assertThat(retrievedUser.get().getName()).isEqualTo("John");
        Optional<CV> retrievedCV = cvRepository.findById(savedCV.getId());
        assertThat(retrievedCV).isPresent();
        assertThat(retrievedCV.get().getActivities().size()).isEqualTo(0);
    }


    @Test
    public void saveCascadeCVTest() {
        //create
        User user = User.builder()
                .name("John")
                .firstName("Doe")
                .birthday(LocalDate.now())
                .email("john.doe@example.com")
                .passwordHash("lehash")
                .build();
        CV cv = CV.builder()
                .user(user)
                .build();

        // Save ONLY user (cascade save cv)
        user.setCv(cv);
        User saveduser = userRepository.save(user);

        // Check if user and cv are saved
        Optional<User> retrievedUser = userRepository.findById(saveduser.getId());
        assertThat(retrievedUser).isPresent();
        assertThat(retrievedUser.get().getName()).isEqualTo("John");

        List<CV> cvs = cvRepository.findAll();
        assertThat(cvs.size()).isGreaterThan(0);
        assertThat(cvs.get(0).getUser()).isNotNull();
    }

    @Test
    public void saveCascadeCVOppositeTest() {
        //create
        User user = User.builder()
                .name("John")
                .firstName("Doe")
                .birthday(LocalDate.now())
                .email("john.doe@example.com")
                .passwordHash("lehash")
                .build();
        CV cv = CV.builder()
                .user(user)
                .build();

        // Save ONLY cv
        cv.setUser(user);
        Exception e = assertThrows(InvalidDataAccessApiUsageException.class, ()->{
            CV savedCv = cvRepository.save(cv);
        });
        assertTrue(e.getMessage().contains("transient instance must be saved before current operation"));
    }














}
